---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: Home
- type: directory
  path: content/home
  label: Hero
  create: all
  match: hero.md
  templates:
  - hero
- type: directory
  path: content/home
  label: About
  create: all
  match: about.md
  templates:
  - about
- type: heading
  label: Content
- type: directory
  path: content/social_icons
  label: Social icons
  create: all
  match: "**/*"
  templates:
  - social-links
- type: directory
  path: content/posts
  label: Blog Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: directory
  path: content/team
  label: Team
  create: all
  match: "**/*"
  templates:
  - team
- type: document
  path: content/data/authors.yaml
  label: Author List
- type: document
  path: content/data/info.json
  label: Info Page
- type: heading
  label: General Config
- type: document
  path: config.json
  label: Site Info
upload_dir: content/images
public_path: "/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv/public"
  instant_preview_command: yarn forestry-preview
